# Generated by Django 5.2.5 on 2025-11-05 00:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_depot_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='commission_versee',
        ),
        migrations.RemoveField(
            model_name='client',
            name='parrain',
        ),
        migrations.CreateModel(
            name='Parrainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_versee', models.BooleanField(default=False)),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
                ('filleul', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lien_parrainage', to='finance.client', verbose_name='Filleul')),
                ('parrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filleuls_parraines', to='finance.client', verbose_name='Parrain')),
            ],
            options={
                'verbose_name': 'Lien de Parrainage',
                'verbose_name_plural': 'Liens de Parrainage',
            },
        ),
    ]
