# Generated by Django 6.0.3 on 2026-06-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_remove_client_commission_versee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='moyen_paiement',
            field=models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('ORANGE', 'Orange Money'), ('BANK', 'Virement bancaire')], default='MTN', max_length=20, verbose_name='Moyen de paiement'),
        ),
        migrations.AddField(
            model_name='client',
            name='nom_beneficiaire',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='numero_portefeuille',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
