# Generated by Django 6.0.3 on 2026-06-07 23:20

import django.db.models.deletion
import django.utils.timezone
import finance.tokens
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_client_moyen_paiement_client_nom_beneficiaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=finance.tokens.generate_token_key, max_length=40, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_token', to='finance.client')),
            ],
            options={
                'verbose_name': 'Token API Client',
            },
        ),
    ]
