# Generated by Django 6.0.3 on 2026-06-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_clienttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='achat_unique',
            field=models.BooleanField(default=False, help_text="Chaque client ne peut acheter ce pack qu'une seule fois.", verbose_name='Achat unique par client'),
        ),
        migrations.AddField(
            model_name='pack',
            name='stock_disponible',
            field=models.PositiveIntegerField(default=0, help_text='Diminue automatiquement à chaque achat client.', verbose_name='Stock disponible'),
        ),
        migrations.AddField(
            model_name='pack',
            name='stock_initial',
            field=models.PositiveIntegerField(default=0, help_text='Nombre total de packs mis en vente.', verbose_name='Stock initial'),
        ),
    ]
