# Generated by Django 6.0.3 on 2026-06-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_init_pack_stock_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='Heure de début (HH:MM)')),
                ('end_time', models.TimeField(help_text='Heure de fin (HH:MM)')),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fenêtre de retrait',
                'verbose_name_plural': 'Fenêtres de retrait',
            },
        ),
    ]
