# Generated by Django 6.0.3 on 2026-06-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_withdrawalwindow'),
    ]

    operations = [
        migrations.AddField(
            model_name='parrainage',
            name='commission_montant',
            field=models.IntegerField(blank=True, help_text='Montant réellement versé au parrain (FCFA)', null=True),
        ),
        migrations.AddField(
            model_name='parrainage',
            name='date_commission',
            field=models.DateTimeField(blank=True, help_text='Date du versement de la commission', null=True),
        ),
    ]
