# Generated by Django 6.0.3 on 2026-06-21 13:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_parrainage_commission_montant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='cycles_restants',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='prochain_revenu_du',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='achat_unique',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='stock_disponible',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='stock_initial',
        ),
        migrations.RemoveField(
            model_name='parrainage',
            name='commission_montant',
        ),
        migrations.RemoveField(
            model_name='parrainage',
            name='date_commission',
        ),
        migrations.AddField(
            model_name='achat',
            name='date_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration du pack"),
        ),
        migrations.AddField(
            model_name='achat',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Pack actif'),
        ),
        migrations.AddField(
            model_name='achat',
            name='montant_total_profit',
            field=models.IntegerField(default=0, verbose_name='Montant total des profits'),
        ),
        migrations.AddField(
            model_name='achat',
            name='profit_versé',
            field=models.BooleanField(default=False, verbose_name='Profit versé'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_pack_expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration du dernier pack"),
        ),
        migrations.AddField(
            model_name='client',
            name='withdrawal_suspended',
            field=models.BooleanField(default=False, verbose_name='Retrait suspendu'),
        ),
        migrations.AlterField(
            model_name='withdrawalwindow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='WithdrawalSuspension',
            fields=[
                ('suspension_id', models.AutoField(primary_key=True, serialize=False)),
                ('suspension_start', models.DateField(default=django.utils.timezone.now, verbose_name='Date de début de suspension')),
                ('suspension_end', models.DateField(verbose_name='Date de fin de suspension')),
                ('reason', models.TextField(default='12 jours après expiration du dernier pack', verbose_name='Raison')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_suspension', to='finance.client')),
            ],
            options={
                'verbose_name': 'Suspension de Retrait',
                'verbose_name_plural': 'Suspensions de Retrait',
            },
        ),
        migrations.CreateModel(
            name='ReferralInfo',
            fields=[
                ('referral_id', models.AutoField(primary_key=True, serialize=False)),
                ('commission_amount', models.IntegerField(default=0, verbose_name='Montant de la commission')),
                ('commission_paid', models.BooleanField(default=False, verbose_name='Commission payée')),
                ('date_creation', models.DateField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_clients', to='finance.client', verbose_name='Parrain')),
                ('sponsored_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_info', to='finance.client', verbose_name='Client parrainé')),
            ],
            options={
                'verbose_name': 'Information de Parrainage',
                'verbose_name_plural': 'Informations de Parrainage',
                'unique_together': {('sponsor', 'sponsored_client')},
            },
        ),
    ]
